# Values surrounded by % (like %UID% and %GID%) are replaced
# by their correct values by the setup script. Leave them be.

version: "3"

services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: "${SONARR_CONTAINER_NAME}"
    environment:
      - PUID=%UID%
      - PGID=%GID%
      - TZ=${SONARR_TIMEZONE}
    volumes:
      - /opt/containers/sonarr:/config
      - ${SONARR_HOST_LIBRARY_PATH}:/library
      - ${RUTORRENT_HOST_DOWNLOADS_PATH}:/downloads
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: "${RADARR_CONTAINER_NAME}"
    environment:
      - PUID=%UID%
      - PGID=%GID%
      - TZ=${RADARR_TIMEZONE}
    volumes:
      - /opt/containers/radarr:/config
      - ${RADARR_HOST_LIBRARY_PATH}:/library
      - ${RUTORRENT_HOST_DOWNLOADS_PATH}:/downloads
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: "${JACKETT_CONTAINER_NAME}"
    environment:
      - PUID=%UID%
      - PGID=%GID%
      - TZ=${JACKETT_TIMEZONE}
    volumes:
      - /opt/containers/jackett:/config
    restart: unless-stopped

  rutorrent:
    image: ghcr.io/linuxserver/rutorrent
    container_name: "${RUTORRENT_CONTAINER_NAME}"
    environment:
      - PUID=%UID%
      - PGID=%GID%
    volumes:
      - /opt/containers/rutorrent:/config
      - ${RUTORRENT_HOST_DOWNLOADS_PATH}:/downloads
    ports:
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: "${CADDY_CONTAINER_NAME}"
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/containers/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/containers/caddy/data:/data
      - /opt/containers/caddy/config:/config
    extra_hosts:
      - "outside:${HOST_IP}"